version: '3'

services:
    api-slg:
        image: api-slg
        container_name: api-slg
        depends_on:
            - db
        build:
            context: ${API_SLG_PATH}
            dockerfile: ${DOCKERFILE}
        volumes:
            - ${API_SLG_PATH}:/src
        ports:
            - ${API_V1_PORT}:${API_V1_PORT}
        environment:
            - PORT=${API_V1_PORT}
            - NODE_ENV=${ENV}
            - CONNECTION_URL=mongodb://db:27017/slg
        restart: 'no'

    api-loi:
        image: api-loi
        container_name: api-loi
        build:
            context: ${API_LOI_PATH}
            dockerfile: ${DOCKERFILE}
        volumes:
            - ${API_LOI_PATH}:/src
        ports:
            - ${API_LOI_V1_PORT}:${API_LOI_V1_PORT}
        environment:
            - PORT=${API_LOI_V1_PORT}
            - NODE_ENV=${ENV}
        restart: 'no'
        depends_on:
            - mysql-loi

    web-portal:
        image: web-portal
        container_name: web-portal
        build:
            context: ${WEB_PORTAL_PATH}
            dockerfile: ${DOCKERFILE}
        depends_on:
            - api-slg
        ports:
            - ${WEB_PORTAL_PORT}:${WEB_PORTAL_PORT}
        volumes:
            - ${WEB_PORTAL_PATH}:/src
        environment:
            - CHOKIDAR_USEPOLLING=true
            - APP_HOSTNAME=${HOSTNAME}/portal
            - PORT=${WEB_PORTAL_PORT}
        restart: 'no'

    web-ofac:
        image: web-ofac
        container_name: web-ofac
        build:
            context: ${WEB_OFAC_PATH}
            dockerfile: ${DOCKERFILE}
        depends_on:
            - api-slg
        ports:
            - ${WEB_OFAC_PORT}:${WEB_OFAC_PORT}
        volumes:
            - ${WEB_OFAC_PATH}:/src
        environment:
            - CHOKIDAR_USEPOLLING=true
            - APP_HOSTNAME=${HOSTNAME}/ofac
            - PORT=${WEB_OFAC_PORT}
        restart: 'no'

    web-loi:
        image: web-loi
        container_name: web-loi
        build:
            context: ${WEB_LOI_PATH}
            dockerfile: ${DOCKERFILE}
        depends_on:
            - api-slg
        ports:
            - ${WEB_LOI_PORT}:${WEB_LOI_PORT}
        volumes:
            - ${WEB_LOI_PATH}:/src
        environment:
            - CHOKIDAR_USEPOLLING=true
            - APP_HOSTNAME=${HOSTNAME}/ofac
            - PORT=${WEB_LOI_PORT}
        restart: 'no'

    web-loi-admin:
        image: web-loi-admin
        container_name: web-loi-admin
        build:
            context: ${WEB_LOI_ADMIN_PATH}
            dockerfile: ${DOCKERFILE}
        depends_on:
            - api-slg
        ports:
            - ${WEB_LOI_ADMIN_PORT}:${WEB_LOI_ADMIN_PORT}
        volumes:
            - ${WEB_LOI_ADMIN_PATH}:/src
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=${WEB_LOI_ADMIN_PORT}
        restart: 'no'

    db:
        image: mongo
        ports:
            - 27018:27017
        volumes:
            - ./nodb:/data/db
        command: mongod --quiet --logpath /dev/null
        restart: 'no'

    mysql-loi:
        image: mysql:5.7
        container_name: mysql-loi
        restart: 'no'
        ports:
            - 3306:3306
        volumes:
            - ${MYSQL_DATA_DIR-./mysql/data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./mysql/logs/mysql}:/var/log/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_HOST=%
            - TZ=Asia/Singapore
        command:
            [
                'mysqld',
                '--wait_timeout=28800',
                '--character-set-server=latin1',
                '--collation-server=latin1_swedish_ci',
                '--innodb_use_native_aio=0',
                '--max_allowed_packet=104857600',
                '--innodb_buffer_pool_size=8006926336',
                '--innodb_log_file_size=134217728',
                '--explicit_defaults_for_timestamp',
            ]

    reverse-proxy:
        image: nginx:1.17.10
        container_name: reverse-proxy
        depends_on:
            - api-slg
            - web-portal
            - web-ofac
            - db
            - mysql-loi
        environment:
            - API_V1_PORT=${API_V1_PORT}
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./reverse-proxy/upstream:/etc/nginx/conf.d/upstream
            - ./reverse-proxy/logs:/var/log/nginx
        ports:
            - ${PROXY_EXPOSE_PORT}:80
        restart: 'no'
